# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-02 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_season_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
        migrations.AddField(
            model_name='match',
            name='week',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
