# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-02 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170702_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='result',
        ),
        migrations.AddField(
            model_name='matchresult',
            name='result',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.MatchResult'),
            preserve_default=False,
        ),
    ]
