# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-02 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170702_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchresult',
            name='match',
        ),
        migrations.AddField(
            model_name='match',
            name='team_1_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team_2_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='MatchResult',
        ),
    ]
