# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-05 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170704_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='make_playoffs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='team',
            name='playoff_bye',
            field=models.FloatField(default=0.0),
        ),
    ]
