# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-06 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_team_championship_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='qualify_for_worlds',
            field=models.FloatField(default=0.0),
        ),
    ]
