# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-04 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nalcs', '0011_auto_20170704_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='predictions',
        ),
        migrations.AddField(
            model_name='teamstats',
            name='team',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='nalcs.Team'),
            preserve_default=False,
        ),
    ]
