# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-06 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nalcs', '0014_auto_20170705_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='win_split',
            field=models.FloatField(default=0.0),
        ),
    ]
