# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-14 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nalcs', '0022_auto_20170713_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('match_wins', models.IntegerField(default=0)),
                ('match_losses', models.IntegerField(default=0)),
                ('game_wins', models.IntegerField(default=0)),
                ('game_losses', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('make_playoffs', models.FloatField(default=0)),
                ('playoff_bye', models.FloatField(default=0)),
                ('win_split', models.FloatField(default=0)),
                ('qualify_for_worlds', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='championship_points',
        ),
        migrations.RemoveField(
            model_name='team',
            name='game_losses',
        ),
        migrations.RemoveField(
            model_name='team',
            name='game_wins',
        ),
        migrations.RemoveField(
            model_name='team',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='team',
            name='make_playoffs',
        ),
        migrations.RemoveField(
            model_name='team',
            name='match_losses',
        ),
        migrations.RemoveField(
            model_name='team',
            name='match_wins',
        ),
        migrations.RemoveField(
            model_name='team',
            name='playoff_bye',
        ),
        migrations.RemoveField(
            model_name='team',
            name='qualify_for_worlds',
        ),
        migrations.RemoveField(
            model_name='team',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='team',
            name='win_split',
        ),
        migrations.AddField(
            model_name='dailyprediction',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nalcs.Team'),
        ),
    ]
