# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-10 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nalcs', '0024_auto_20180310_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='game_number',
        ),
        migrations.AlterField(
            model_name='match',
            name='best_of',
            field=models.IntegerField(default=1),
        ),
    ]
