# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-10 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nalcs', '0025_auto_20180310_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
