# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-02 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('na_lcs', '0002_auto_20170701_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='na_lcs.Season'),
            preserve_default=False,
        ),
    ]
