# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-02 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('na_lcs', '0006_auto_20170702_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchresult',
            old_name='result',
            new_name='match',
        ),
    ]
