# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-03 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('na_lcs', '0009_auto_20170702_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
