# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-04 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('na_lcs', '0012_auto_20170704_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamstats',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='game_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='game_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='match_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='match_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='TeamStats',
        ),
    ]
