# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-07 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('na_lcs', '0017_team_qualify_for_worlds'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='spring_championship_points',
            field=models.IntegerField(default=0),
        ),
    ]
